---
title: "Data_Clean"
author: "Nir Ben Laufer"
date: "2023-04-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(readr)

```

```{r Read in Data}
#Dataset from https://www.kaggle.com/datasets/osmi/mental-health-in-tech-survey?resource=download

survey <- read_csv(here::here("survey.csv"))

head(survey)
```

```{r view data}

Gender <- survey |> 
  select(Gender) |> 
  filter(Gender != "Male" & Gender != "Female") |> 
  filter(!duplicated(Gender))

Gender

Age <- survey |> 
  select(Age) |> 
  filter(Age < 5 | Age > 122)

Age

```

```{r clean}

# Comments from class 4/25
# use case_when instead of nested ifs
# OR make a spreadsheet with all responses and left join
# It's okay to randomly drop rows (e.g. because the datapoints look fishy, like the person who said they were 8 yrs old or the person who answered the first response on every dropdown)
# It's dangerous/bad practice to systematically drop datapoints because that gives you biased data

clean_data <- survey %>%
  mutate(
    Gender = case_when(Gender == "Male" | Gender == "M" | Gender == "male" | 
                              Gender == "m" | Gender == "maile" | Gender == "Cis Male" | 
                              Gender == "Mal" | Gender == "Male (CIS)" | 
                              Gender == "Make" | Gender == "Man" | Gender == "msle" | 
                              Gender == "Mail" | Gender == "cis male" | 
                              Gender == "Malr" | Gender == "Cis Man"
                            ~ "Male",
            Gender == "Female" | Gender == "female" | Gender == "F" | 
                             Gender == "Woman" | Gender == "f" | Gender == "Femake" | 
                             Gender == "woman" | Gender == "cis-female/femme" | 
                             Gender == "Female (cis)" | Gender == "femail" 
              ~ "Female",
            Gender == "Male-ish" | Gender == "something kinda male?" | 
                               Gender == "male leaning androgynous" | 
                               Gender == "Guy (-ish) ^_^" | 
                               Gender == "ostensibly male, unsure what that really means"
              ~ "Leaning Male",
            Gender == "queer/she/they" 
              ~ "Leaning Female",
            Gender == "Trans-female" | Gender == "Trans woman" | 
                                   Gender == "Female (trans)" 
              ~ "Trans Female", 
            Gender == "non-binary" | Gender == "All" | 
                                     Gender == "Enby" | Gender == "fluid" | 
                                     Gender == "Genderqueer" | Gender == "Androgyne" | 
                                     Gender == "Agender" | Gender == "queer"
              ~ "Nonbinary",
            TRUE ~ "Did Not Specify")) |> 
  mutate(Age = ifelse(Age < 18 | Age > 100,
                      NA,
                      Age),
         across(.cols = self_employed:obs_consequence, .fns = ~ as.factor(.x)))



saveRDS(clean_data, file = "clean_data.RDS")

```
