---
title: "Shiny_App"
author: "Ben Laufer, Josh Rowe, Roee Morag"
date: "2023-04-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(shiny)
library(dplyr)
library(ggplot2)
library(leaflet)
library(geojsonio)
library(plotly)
library(maps)
library(readr)
```

```{r Read in Data}
#Dataset from https://www.kaggle.com/datasets/osmi/mental-health-in-tech-survey?resource=download

survey <- read_csv(here::here("survey.csv"))
```

```{r view data}
#Filter all data that is not in the "default" range/bound
Gender <- survey |> 
  select(Gender) |> 
  filter(Gender != "Male" & Gender != "Female") |> 
  filter(!duplicated(Gender))

Age <- survey |> 
  select(Age) |> 
  filter(Age < 5 | Age > 122)
```

```{r clean}
# Comments from class 4/25
# use case_when instead of nested ifs
# OR make a spreadsheet with all responses and left join
# It's okay to randomly drop rows (e.g. because the datapoints look fishy, like the person who said they were 8 yrs old or the person who answered the first response on every dropdown)
# It's dangerous/bad practice to systematically drop datapoints because that gives you biased data

clean_data <- survey %>%
  mutate(
    Gender = case_when(Gender == "Male" | Gender == "M" | Gender == "male" | 
                              Gender == "m" | Gender == "maile" | Gender == "Cis Male" | 
                              Gender == "Mal" | Gender == "Male (CIS)" | 
                              Gender == "Make" | Gender == "Man" | Gender == "msle" | 
                              Gender == "Mail" | Gender == "cis male" | 
                              Gender == "Malr" | Gender == "Cis Man"
                            ~ "Male",
            Gender == "Female" | Gender == "female" | Gender == "F" | 
                             Gender == "Woman" | Gender == "f" | Gender == "Femake" | 
                             Gender == "woman" | Gender == "cis-female/femme" | 
                             Gender == "Female (cis)" | Gender == "femail" 
              ~ "Female",
            Gender == "Male-ish" | Gender == "something kinda male?" | 
                               Gender == "male leaning androgynous" | 
                               Gender == "Guy (-ish) ^_^" | 
                               Gender == "ostensibly male, unsure what that really means"
              ~ "Leaning Male",
            Gender == "queer/she/they" 
              ~ "Leaning Female",
            Gender == "Trans-female" | Gender == "Trans woman" | 
                                   Gender == "Female (trans)" 
              ~ "Trans Female", 
            Gender == "non-binary" | Gender == "All" | 
                                     Gender == "Enby" | Gender == "fluid" | 
                                     Gender == "Genderqueer" | Gender == "Androgyne" | 
                                     Gender == "Agender" | Gender == "queer"
              ~ "Nonbinary",
            TRUE ~ "Did Not Specify")) |> 
  mutate(Age = ifelse(Age < 18 | Age > 100,
                      NA,
                      Age),
         across(.cols = self_employed:obs_consequence, .fns = ~ as.factor(.x))) |> 
  select(Age:obs_consequence)


saveRDS(clean_data, file = "clean_data.RDS")
```

```{r clean_data read in}
#Takes the cleaned clean_data from the previous R markdown
clean_data <- readRDS(here::here("clean_data.RDS"))

survey_questions <- data.frame(Variable_Name = c("Age", "Gender", "Country", "state", 
                                       "self_employed", "family_history", 
                                       "treatment", "work_interfere", 
                                       "no_employees", "remote_work", 
                                       "tech_company", "benefits", 
                                       "care_options", "wellness_program", 
                                       "seek_help", "anonymity", "leave", 
                                       "mental_health_consequence", 
                                       "phys_health_consequence", "coworkers", 
                                       "supervisor", "mental_health_interview", 
                                       "phys_health_interview", 
                                       "mental_vs_physical", "obs_consequence"),
                               Variable_Explanation= c(NA, NA, NA, NA, "Are you self-employed?", 
                                            "Do you have a family history of mental illness?", 
                                            "Have you sought treatment for a mental health condition?", 
                                            "If you have a mental health condition, do you feel that it interferes with your work?", 
                                            "How many employees does your company or organization have?", 
                                            "Do you work remotely (outside of an office) at least 50% of the time?", 
                                            "Is your employer primarily a tech company/organization?", 
                                            "Does your employer provide mental health benefits?", 
                                            "Do you know the options for mental health care your employer provides?", 
                                            "Has your employer ever discussed mental health as part of an employee wellness program?", 
                                            "Does your employer provide resources to learn more about mental health issues and how to seek help?", 
                                            "Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources?", 
                                            "How easy is it for you to take medical leave for a mental health condition?", 
                                            "Do you think that discussing a mental health issue with your employer would have negative consequences?", 
                                            "Do you think that discussing a physical health issue with your employer would have negative consequences?", 
                                            "Would you be willing to discuss a mental health issue with your coworkers?", 
                                            "Would you be willing to discuss a mental health issue with your direct supervisor(s)?", 
                                            "Would you bring up a mental health issue with a potential employer in an interview?", 
                                            "Would you bring up a physical health issue with a potential employer in an interview?", 
                                            "Do you feel that your employer takes mental health as seriously as physical health?", 
                                            "Have you heard of or observed negative consequences for coworkers with mental health conditions in your workplace?"))


```

```{r Cleaning for Map}
state_lookup <- setNames(state.name, state.abb)
# Filter data to include only states, we are only interested in thee United States
clean_data_states <- clean_data
clean_data_states$state_full <- state_lookup[as.character(clean_data$state)]
clean_data_states <- clean_data_states[complete.cases(clean_data_states$state_full), ]
  
#Using maps package, 
state.center <- as.data.frame(state.center)
state.center$state_full <- state.name
    
clean_data_merged <- merge(state.center, clean_data_states, by = "state_full")

```

```{r UI}
# Define UI
ui <- fluidPage(
  titlePanel("My Shiny App"),
  navbarPage(
    "Header Selections",
    #The code below creates the ggplot tab panel. This one shows the data - presented with either a bar graph or dot plot in ggplot
    
    tabPanel("ggplot",
             sidebarPanel(
              selectInput("country", "Select country:", choices = c("All", unique(clean_data$Country))),
              selectInput("gender", "Select gender", choices = c("All", unique(clean_data$Gender))),
              selectInput("variable", "Select variable:", choices = unique(names(clean_data)[4:ncol(clean_data)])),
              selectInput("plot", "Select plot type:", choices = unique(c("dot plot", "bar graph"))),
              dataTableOutput("questions_table")
              ),
          
              mainPanel(
               tabPanel("Table", dataTableOutput("table")),
               tabPanel("Plot", plotOutput("ggplot"))
              )
          ),
    
    #The code below presents the data - when viewing the United States - as a Leaflet map
    tabPanel("USA Map",
             sidebarPanel(
              selectInput("map_gender", "Select gender:", choices = c("All", unique(clean_data$Gender))),
              selectInput("map_variable", "Select variable:", choices = unique(names(clean_data)[3:ncol(clean_data)])),
          ),
          mainPanel(
          leafletOutput("map"))
      ),
    #The code below presents the data through Plotly
    tabPanel("Plotly Graph",
             sidebarPanel(
              selectInput("plotly_variable", "Select variable:", choices = unique(names(clean_data)[2:ncol(clean_data)]))
              ),
          
              mainPanel(
               tabPanel("Plotly", plotlyOutput("plotly"))
              )
          )
)
)
#Refrenced Chat GPT
```

```{R Server}
# Define server
server <- function(input, output) {

  # Filter data by country and gender
  clean_data_filtered <- reactive({
    if (input$gender == "All" && input$country != "All") {
      clean_data %>%
        filter(Country == input$country)
    } 
    else if (input$gender != "All" && input$country != "All") {
      clean_data %>%
        filter(Country == input$country, Gender == input$gender)
    }
    else if (input$gender != "All" && input$country == "All") {
      clean_data %>%
        filter(Gender == input$gender)
    }
    else {
      clean_data
    }
  })
  
  # Summarize data by variable and calculate frequency percentages
  clean_data_summary <- reactive({
    clean_data_filtered() %>%
      group_by(!!sym(input$variable)) %>%
      summarize(Freq = n()) %>%
      mutate(Percentage = Freq / sum(Freq) * 100)
  })
  
  # Generate table
  output$table <- renderDataTable({
    clean_data_summary() %>%
      arrange(desc(Freq))
  }, options = list(lengthMenu = c(5, 10, 15)))
  
  
  # Generate table describing the variables in the data
  output$questions_table <- renderDataTable({
    survey_questions
  }, options = list(pageLength = 5, 
                    dom = 'pt'))
  
# Generate bar graph
  output$ggplot <- renderPlot({
    if(input$plot == "bar graph"){
      ggplot(clean_data_summary(), aes(x = reorder(!!sym(input$variable), -Percentage), 
                                       y = Percentage)) +
        geom_bar(stat = "identity", 
                 position = "dodge",
                 fill = "navy") + 
        labs(x = input$variable)
    }
      
    else if(input$plot == "dot plot"){
      ggplot(clean_data_summary(), aes(x = reorder(!!sym(input$variable), -Percentage), 
                                       y = Percentage)) +
        geom_point(color = "navy",
                   size = 6) + 
        labs(x = input$variable)
    }
  })
  
  output$plotly <- renderPlotly({
      #Create plotly, using dataset from prev. chunk
      fig <- clean_data_filtered() %>%
        plot_ly(
          type = 'scatter',
          mode = 'markers',
          x = ~Age,
          y = as.formula(paste0("~", input$plotly_variable)),
          color = ~Country,
          text = ~Country,
          hovertemplate = paste(
            "<b>%{text}</b><br><br>",
            "{Age}: %{x:}<br>",
            "{Variable Selected Reponse}: %{y:input$plotly_variable)}<br>",
            "<extra></extra>"
            )
        )
  })
  
    # Create the Leaflet map
    
    clean_data_map_filtered <- reactive({
    if (input$gender == "All" && input$country != "All") {
      clean_data_merged %>%
        filter(Country == input$country)
    } 
    else if (input$gender != "All" && input$country != "All") {
      clean_data_merged %>%
        filter(Country == input$country, Gender == input$gender)
    }
    else if (input$gender != "All" && input$country == "All") {
      clean_data_merged %>%
        filter(Gender == input$gender)
    }
    else {
      clean_data_merged
    }
  })

    
     clean_data_map_summary <- reactive({
    clean_data_map_filtered() %>%
      group_by(!!sym(input$map_variable)) %>%
      summarize(Freq = n()) %>%
      mutate(Percentage = Freq / sum(Freq) * 100) 
     })
     

    output$map <- renderLeaflet({
      
        leaflet(data = clean_data_map_summary()) %>%  
        setView(-96, 37.8, 4) %>% 
        addTiles() %>% 
        addCircles(lng = clean_data_merged$x, lat = clean_data_merged$y, weight = 1, radius = 15000 * sqrt(clean_data_map_summary()$Percentage))
        
        
    })
    
  }
# Referenced Chat GPT
```

```{r app}
# Run the app
shinyApp(ui = ui, server = server)

```
