---
title: "Shiny Saved"
author: "Nir Ben Laufer"
date: '2023-04-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(shiny)
library(dplyr)
library(ggplot2)
library(leaflet)
library(geojsonio)

```


```{r clean_data read in}

#Takes the cleaned clean_data from the previous R markdown
clean_data <- readRDS(here::here("clean_data.RDS"))
head(clean_data)
usa_map <- geojsonio::geojson_read("https://rstudio.github.io/leaflet/json/us-states.geojson", what = "sp")

```


```{r}
# Define UI
ui <- fluidPage(
  titlePanel("My Shiny App"),
  navbarPage(
    "Header Selections",
    tabPanel("ggplot",
             sidebarPanel(
              selectInput("country", "Select country:", choices = unique(clean_data$Country)),
              selectInput("gender", "Select gender:", choices = c("All", unique(clean_data$Gender))),
              selectInput("variable", "Select variable:", choices = unique(names(clean_data)[2:ncol(clean_data)])),
              selectInput("plot", "Select plot type:", choices = unique(c("scatter plot", "bar graph")))
          ),
          
              mainPanel(
               tabPanel("Table", dataTableOutput("table")),
               tabPanel("Plot", plotOutput("ggplot"))
             )
          ),
      
    tabPanel("USA Map",
             sidebarPanel(
              selectInput("gender", "Select gender:", choices = c("All", unique(clean_data$Gender))),
              selectInput("variable", "Select variable:", choices = unique(names(clean_data)[2:ncol(clean_data)])),
          ),
          mainPanel(
          leafletOutput("map"))
      )       
    )
)


# Define server
server <- function(input, output) {
  
  # Filter data by country and gender
  clean_data_filtered <- reactive({
    if (input$gender == "All") {
      clean_data %>%
        filter(Country == input$country)
    } else {
      clean_data %>%
        filter(Country == input$country, Gender == input$gender)
    }
  })
  
  # Summarize data by variable and calculate frequency percentages
  clean_data_summary <- reactive({
    clean_data_filtered() %>%
      group_by(!!sym(input$variable)) %>%
      summarize(Freq = n()) %>%
      mutate(Percentage = Freq / sum(Freq) * 100)
  })
  
  # Generate table
  output$table <- renderDataTable({
    clean_data_summary() %>%
      arrange(desc(Freq)) %>%
      head()
  } , options = list(lengthMenu = c(5, 10, 15)))
  
# Generate bar graph
  output$ggplot <- renderPlot({
    if(input$plot == "bar graph"){
      ggplot(clean_data_summary(), aes(x = !!sym(input$variable), y = Percentage)) +
      geom_bar(stat = "identity", position = "dodge")
    }
  })
  
  
    output$map <- renderLeaflet({
        # code from https://rstudio.github.io/leaflet/choropleths.html
        m <- leaflet(usa_map) |> 
          setView(-96, 37.8, 4) |> 
          addProviderTiles("MapBox", options = providerTileOptions(
            id = "mapbox.light",
            accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN'))) 
        
        bins <- c(0, 10, 20, 50, 100, 200, 500, 1000, Inf)
        pal <- colorBin("YlOrRd", domain = input$variable, bins = bins)
        m %>% addPolygons(
          fillColor = ~pal(density),
          weight = 2,
          opacity = 1,
          color = "white",
          dashArray = "3",
          fillOpacity = 0.7)
    })
  
  
}
# Run the app
shinyApp(ui = ui, server = server)
# Refrenced Chat GPT
```
