on:
  push:
    branches:
      - main

name: Deploy Shiny app to shinyapps.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      R_LIBS_USER: ${{ github.workspace }}/Rlibs

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install rsconnect
        run: |
          dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE)
          install.packages("rsconnect", lib = Sys.getenv("R_LIBS_USER"))
        shell: Rscript {0}

      - name: Deploy app
        env:
          SHINYAPPS_NAME: myApp
          SHINYAPPS_ACCOUNT: blauf
          SHINYAPPS_TOKEN: ${{ secrets.TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SECRET }}
        run: |
          .libPaths(Sys.getenv("R_LIBS_USER"))
          rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_ACCOUNT"),
                                    token=Sys.getenv("SHINYAPPS_TOKEN"),
                                    secret=Sys.getenv("SHINYAPPS_SECRET"))
          rsconnect::deployApp(appName=Sys.getenv("SHINYAPPS_NAME"))
        shell: Rscript {0}
