name: Deploy to shinyapps.io

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SHINYAPPS_NAME: myApp
      SHINYAPPS_ACCOUNT: blauf
      SHINYAPPS_TOKEN: ${{ secrets.TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SECRET }}
      R_LIBS_USER: /home/runner/work/_temp/Library

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'  # match your runtime.txt

      - name: Install rsconnect
        run: |
          install.packages("rsconnect")
        shell: Rscript {0}

      - name: Deploy to shinyapps.io
        run: |
          rsconnect::setAccountInfo(
            name = Sys.getenv("SHINYAPPS_ACCOUNT"),
            token = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )
          rsconnect::deployApp(appDir = ".", appName = Sys.getenv("SHINYAPPS_NAME"), forceUpdate = TRUE)
        shell: Rscript {0}
