on:
  push:
    branches:
      - main

name: Deploy Shiny app to shinyapps.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      R_LIBS_USER: ${{ github.workspace }}/.Rlibrary

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev

      - name: Install rsconnect
        run: |
          mkdir -p "$R_LIBS_USER"
          Rscript -e 'install.packages("rsconnect", lib = Sys.getenv("R_LIBS_USER"), repos = "https://cloud.r-project.org")'

      - name: Deploy to ShinyApps.io
        env:
          SHINYAPPS_NAME: myApp
          SHINYAPPS_ACCOUNT: blauf
          SHINYAPPS_TOKEN: ${{ secrets.TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SECRET }}
        run: |
          Rscript -e '
            .libPaths(Sys.getenv("R_LIBS_USER"));
            library(rsconnect);
            rsconnect::setAccountInfo(
              name = Sys.getenv("SHINYAPPS_ACCOUNT"),
              token = Sys.getenv("SHINYAPPS_TOKEN"),
              secret = Sys.getenv("SHINYAPPS_SECRET")
            );
            rsconnect::deployApp(appName = Sys.getenv("SHINYAPPS_NAME"))'
